name: BedTech
version: 1.0
author: Nous
main: poly.bedtech.LimaMain
api-version: 1.13
commands:
  bonjour:
    description: Hello World
    permission: bonjour.use
  lima:
    description: Lima command
    permission: lima.use